name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: bnet.extensions.microsoft.dependencyinjection
      CONTAINER_NAME: bnet.extensions.microsoft.dependencyinjectioncontainer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"          
    - name: Build and start container from build image
      run: |
        docker build --target pack --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }} .
        docker run --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
    - name: Copy container build output
      run:
        docker cp ${{ env.CONTAINER_NAME }}:/testresults TestResults
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: dotnet Tests            # Name of the check run which will be created
        path: TestResults/*.trx    # Path to test results
        reporter: dotnet-trx        # Format of test results
